import { useEffect, useState } from 'react'
import { invoiceApi, partChargeApi } from '../services/api'

function InvoiceDetail({ invoice }) {
  if (!invoice) return null
  return <section className="portal-card"><h2>{invoice.invoiceNumber || `Job #${invoice.jobCardId} draft`}</h2><p>Customer #{invoice.customerId} · Vehicle: {invoice.vehicleRegistrationNumber || 'Not provided'} · Job: {invoice.jobCardNumber || invoice.jobCardId}</p><div className="portal-table-wrapper"><table className="portal-table"><thead><tr><th>Type</th><th>Description</th><th>Qty</th><th>Unit Price</th><th>Total</th></tr></thead><tbody>{invoice.chargeLines?.length ? invoice.chargeLines.map(line => <tr key={line.id}><td>{line.chargeType}</td><td>{line.description}</td><td>{line.quantity}</td><td>{Number(line.unitPrice).toFixed(2)}</td><td>{Number(line.lineTotal).toFixed(2)}</td></tr>) : <tr><td colSpan="5">No charge lines yet.</td></tr>}</tbody></table></div><h2>Total: {Number(invoice.totalAmount || 0).toFixed(2)}</h2></section>
}

export default function InvoicesPage() {
  const [eligible, setEligible] = useState([])
  const [selected, setSelected] = useState(null)
  const [form, setForm] = useState({ type: 'service', description: '', quantity: '1', unitPrice: '' })
  const [error, setError] = useState('')
  const [notice, setNotice] = useState('')
  const [loading, setLoading] = useState(true)
  const load = async () => { try { setLoading(true); setError(''); setEligible(await invoiceApi.getEligibleJobs()) } catch (e) { setError(e.message || 'Unable to load eligible jobs.') } finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  const open = async job => { try { setError(''); setNotice(''); setSelected(await partChargeApi.getInvoice(job.jobCardId)) } catch (e) { setError(e.message || 'Unable to open the invoice draft.') } }
  const addCharge = async e => { e.preventDefault(); if (!selected) return; try { const data = { description: form.description, quantity: Number(form.quantity), unitPrice: Number(form.unitPrice) }; const result = form.type === 'service' ? await partChargeApi.addService(selected.jobCardId, data) : await partChargeApi.addLabour(selected.jobCardId, data); setSelected(result); setForm({ ...form, description: '', quantity: '1', unitPrice: '' }); setNotice('Charge added.') } catch (err) { setError(err.message || 'Unable to add charge.') } }
  const generate = async () => { if (!selected || !window.confirm('Generate the final invoice? It cannot be changed afterwards.')) return; try { setError(''); const result = await invoiceApi.generate(selected.jobCardId); setSelected(result); setNotice(`Invoice ${result.invoiceNumber} generated successfully.`); await load() } catch (e) { setError(e.message || 'Unable to generate invoice.') } }
  return <main className="portal-main"><header className="portal-topbar"><div><span className="portal-eyebrow">ACCOUNTS</span><h1>Invoice Generation</h1></div><button className="portal-primary-button" onClick={load}>Refresh</button></header><div className="portal-content">{error && <div className="portal-error">{error}</div>}{notice && <div className="portal-card">{notice}</div>}<section className="portal-card"><h2>Eligible completed jobs</h2>{loading ? <p>Loading eligible jobs…</p> : eligible.length === 0 ? <p>No completed jobs are waiting for billing.</p> : <div className="portal-table-wrapper"><table className="portal-table"><thead><tr><th>Job</th><th>Customer</th><th>Vehicle</th><th /></tr></thead><tbody>{eligible.map(job => <tr key={job.id}><td>{job.jobCardNumber || `#${job.jobCardId}`}</td><td>#{job.customerId}</td><td>{job.vehicleRegistrationNumber}</td><td><button className="portal-primary-button" onClick={() => open(job)}>Open</button></td></tr>)}</tbody></table></div>}</section>{selected && !selected.isGenerated && <section className="portal-card"><h2>Add service or labour charge</h2><form className="inventory-form" onSubmit={addCharge}><label>Type<select value={form.type} onChange={e => setForm({ ...form, type: e.target.value })}><option value="service">Service</option><option value="labour">Labour</option></select></label><label>Description<input required value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} /></label><label>Quantity / hours<input required type="number" min="0.01" step="0.01" value={form.quantity} onChange={e => setForm({ ...form, quantity: e.target.value })} /></label><label>Unit price<input required type="number" min="0" step="0.01" value={form.unitPrice} onChange={e => setForm({ ...form, unitPrice: e.target.value })} /></label><div className="inventory-form-actions"><button className="portal-primary-button">Add charge</button><button type="button" className="portal-primary-button" onClick={generate}>Generate invoice</button></div></form></section>}<InvoiceDetail invoice={selected} /></div></main>
}
