using BillingService.Data;
using BillingService.DTOs;
using BillingService.Models;
using Microsoft.EntityFrameworkCore;
namespace BillingService.Services;
public interface IInvoiceService { Task<InvoiceResponseDto> GetByJobAsync(int jobCardId, CancellationToken ct = default); Task<InvoiceResponseDto> AddManualAsync(int jobCardId, ChargeType type, AddManualChargeDto dto, CancellationToken ct = default); Task AddPartAsync(int jobCardId, int issueId, string description, decimal quantity, decimal unitPrice, CancellationToken ct = default); }
public class InvoiceService(BillingDbContext db) : IInvoiceService
{
 public async Task<InvoiceResponseDto> GetByJobAsync(int jobCardId, CancellationToken ct = default) { var invoice = await db.Invoices.Include(x => x.ChargeLines).AsNoTracking().SingleOrDefaultAsync(x => x.JobCardId == jobCardId, ct); return invoice is null ? new InvoiceResponseDto { JobCardId = jobCardId } : Map(invoice); }
 public async Task<InvoiceResponseDto> AddManualAsync(int jobCardId, ChargeType type, AddManualChargeDto dto, CancellationToken ct = default) { if (jobCardId <= 0 || (type != ChargeType.Service && type != ChargeType.Labour) || string.IsNullOrWhiteSpace(dto.Description) || dto.Quantity <= 0 || dto.UnitPrice < 0) throw new InvalidOperationException("Description is required, quantity must be greater than zero, and unit price cannot be negative."); var invoice = await GetOrCreateAsync(jobCardId, ct); invoice.ChargeLines.Add(NewLine(type, dto.Description, dto.Quantity, dto.UnitPrice, null)); await RecalculateAndSaveAsync(invoice, ct); return Map(invoice); }
 public async Task AddPartAsync(int jobCardId, int issueId, string description, decimal quantity, decimal unitPrice, CancellationToken ct = default) { if (jobCardId <= 0 || issueId <= 0 || quantity <= 0 || unitPrice < 0 || string.IsNullOrWhiteSpace(description)) throw new InvalidOperationException("Invalid issued-part charge data."); var invoice = await GetOrCreateAsync(jobCardId, ct); if (invoice.ChargeLines.Any(x => x.SourceReferenceId == issueId.ToString())) return; invoice.ChargeLines.Add(NewLine(ChargeType.Part, description, quantity, unitPrice, issueId.ToString())); await RecalculateAndSaveAsync(invoice, ct); }
 private async Task<Invoice> GetOrCreateAsync(int jobCardId, CancellationToken ct) { var invoice = await db.Invoices.Include(x => x.ChargeLines).SingleOrDefaultAsync(x => x.JobCardId == jobCardId, ct); if (invoice is not null) return invoice; invoice = new Invoice { JobCardId = jobCardId }; db.Invoices.Add(invoice); await db.SaveChangesAsync(ct); return invoice; }
 private static ChargeLine NewLine(ChargeType type, string description, decimal quantity, decimal unitPrice, string? source) => new() { ChargeType = type, Description = description.Trim(), Quantity = quantity, UnitPrice = unitPrice, LineTotal = quantity * unitPrice, SourceReferenceId = source };
 private async Task RecalculateAndSaveAsync(Invoice invoice, CancellationToken ct) { invoice.TotalAmount = invoice.ChargeLines.Sum(x => x.LineTotal); invoice.UpdatedAt = DateTime.UtcNow; await db.SaveChangesAsync(ct); }
 private static InvoiceResponseDto Map(Invoice x) => new() { Id = x.Id, JobCardId = x.JobCardId, TotalAmount = x.TotalAmount, ChargeLines = x.ChargeLines.OrderBy(x => x.CreatedAt).Select(x => new ChargeLineResponseDto { Id = x.Id, ChargeType = x.ChargeType.ToString().ToUpperInvariant(), Description = x.Description, Quantity = x.Quantity, UnitPrice = x.UnitPrice, LineTotal = x.LineTotal }).ToList() };
}
